version: "3"
services:
  app:
    build: "."
    ports:
      - "5077:5077"
    environment:
      - CONFIG_CENTER_ENABLED
      - VAULT_URL
      - VAULT_CRT
      - VAULT_TOKEN
      - OPEN_TELEMETRY_ENABLED
      - DATASET_FILE_FOLDER
      - DATASET_SCHEMA_FOLDER
      - DATASET_CODE_REGEX
      - ROOT_PATH
      - CORE_ZONE_LABEL
      - GREEN_ZONE_LABEL
      - MINIO_OPENID_CLIENT
      - MINIO_ENDPOINT
      - MINIO_HTTPS
      - KEYCLOAK_URL
      - NEO4J_SERVICE
      - QUEUE_SERVICE
      - CATALOGUING_SERVICE
      - ENTITYINFO_SERVICE
      - ELASTIC_SEARCH_SERVICE
      - UTILITY_SERVICE
      - gm_queue_endpoint
      - gm_username
      - gm_password
      - DATA_OPS_UTIL
      - SEND_MESSAGE_URL
      - RDS_HOST
      - RDS_PORT
      - RDS_DBNAME
      - RDS_USER
      - RDS_SCHEMA_DEFAULT
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - DOWNLOAD_TOKEN_EXPIRE_AT
      - MAX_PREVIEW_SIZE
      - ESSENTIALS_NAME
      - ESSENTIALS_TPL_NAME

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
