version: "3.8"

services:
  app:
    build:
      target: dataset-image
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "127.0.0.1:5077:5077"
    depends_on:
      - postgres
      - redis
    env_file:
      - '.env'

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataset
    expose:
      - 5432
    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  alembic:
    build:
      target: alembic-image
    env_file:
      - '.env'
    volumes:
      - ./migrations/:/app/migrations/
      - ./app/:/app/app/
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  redis:
    driver: local
  postgres-data:
